app:
  jwt:
    access:
      secret: 423F4528482B4D6250655368566D597133743677397A24432646294A404E635266546A576E5A7234753778214125442A472D4B6150645367566B587032733576
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: apiGateway
  cloud:
    gateway:
      routes:
        - id: queries
          uri: lb://queries
          predicates:
            - Path=/queries/**,/apps/**,/fields/**,/tables/**
          filters:
            - AuthenticationFilter
        - id: authorization
          uri: http://localhost:8181
          predicates:
            - Path=/auth/**
        - id: ocb
          uri: lb://ocb
          predicates:
            - Path=/ocb/**
          filters:
            - AuthenticationFilter
        - id: voucher
          uri: lb://voucher
          predicates:
            - Path=/voucher/**
          filters:
            - AuthenticationFilter
        - id: eureka-server
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
        - id: eureka-server-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**

logging:
  level:
    root: info
    org:
      springframework:
        cloud:
          gateway:
            - trace
            - route:
                RouteDefinitionLocator: info
